# Generated by Django 4.2.16 on 2025-01-23 17:50

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[users.models.validate_date_of_birth]),
        ),
    ]
