# Generated by Django 4.2.16 on 2025-02-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
