# Generated by Django 4.2.16 on 2025-02-08 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyAnatomicalRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RadiologyModality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RadiologyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_ana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_models.bodyanatomicalregion')),
                ('radio_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_models.radiologymodality')),
            ],
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_path', models.FileField(max_length=255, upload_to='uploaded_files/models/')),
                ('active_status', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=50)),
                ('radio_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='ai_models.radiologydetails')),
            ],
        ),
    ]
