# Generated by Django 4.2.16 on 2025-04-25 16:28

import ai_models.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='model_path',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='version',
        ),
        migrations.CreateModel(
            name='AIModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=ai_models.models.model_file_upload_path)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ai_models.aimodel')),
            ],
        ),
    ]
